
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  search: /search
  About: /about_me

# Miscelaneous
favicon: /logo.png

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content_limit: 140

search:
  path: search.xml
  field: post

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js
sitemap:
    path: sitemap.xml

google_analytics: UA-86660611-1
baidu_analytics: 7d0f5601cb689e2181a85adf3bc4ea23

# switch
show_excerpt: true
show_date: true
#footer
github: https://github.com/wansho
